version: '3.8'
services:

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=example

  redis:
    image: redis
    command: "redis-server --appendonly yes"

  app:
    image: pythonflasklogin:latest
    depends_on:
      - mariadb
      - redis
    ports:
      - 8080:80
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root

